using System;
using fibonacci.Models;

namespace fibonacci.Services
{
    public class FibonacciService : IFibonacciService
    {
        private readonly IFibonacciCalculator _calculator;
        private readonly IHostInfoProvider _hostInfo;

        public FibonacciService(
            IFibonacciCalculator calculator,
            IHostInfoProvider hostInfo)
        {
            _calculator = calculator;
            _hostInfo = hostInfo;
        }

        public FibonacciResult Calculate(int element)
        {
            var value = _calculator.Fibonacci(element);
            var ipAddress = _hostInfo.GetIpAddress();
            var currentUTC = _hostInfo.GetCurrentUTC();
            var metadata = $"Generated by {ipAddress} at {currentUTC}";
            
            var result = new FibonacciResult();
            result.Element = element;
            result.Value = value;
            result.Metadata = metadata;

            return result;
        }
    }
}